// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaozzkDzF9lp_afz804XTo7w7ZBag3x3o',
    appId: '1:53162272574:web:32225924cca8f7d6aa2e6f',
    messagingSenderId: '53162272574',
    projectId: 'attendancetracker-74527',
    authDomain: 'attendancetracker-74527.firebaseapp.com',
    storageBucket: 'attendancetracker-74527.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDR_b3Hd8ZisDuI2kG2TSq0MvNYGYdP9Qg',
    appId: '1:53162272574:android:2eabf7d6cd258ce1aa2e6f',
    messagingSenderId: '53162272574',
    projectId: 'attendancetracker-74527',
    storageBucket: 'attendancetracker-74527.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGyGrsatiZiESrqGegGQQskm5M0woeHi8',
    appId: '1:53162272574:ios:8d8fd65301a76146aa2e6f',
    messagingSenderId: '53162272574',
    projectId: 'attendancetracker-74527',
    storageBucket: 'attendancetracker-74527.firebasestorage.app',
    iosBundleId: 'com.example.attendanceAppNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGyGrsatiZiESrqGegGQQskm5M0woeHi8',
    appId: '1:53162272574:ios:8d8fd65301a76146aa2e6f',
    messagingSenderId: '53162272574',
    projectId: 'attendancetracker-74527',
    storageBucket: 'attendancetracker-74527.firebasestorage.app',
    iosBundleId: 'com.example.attendanceAppNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBaozzkDzF9lp_afz804XTo7w7ZBag3x3o',
    appId: '1:53162272574:web:4e4fc290cc8cdd6caa2e6f',
    messagingSenderId: '53162272574',
    projectId: 'attendancetracker-74527',
    authDomain: 'attendancetracker-74527.firebaseapp.com',
    storageBucket: 'attendancetracker-74527.firebasestorage.app',
  );
}